services:
    postgresql:
        image: postgres:15
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
            TZ: 'Asia/Seoul'
    redis:
        image: redis:7.2-alpine
        restart: always
        volumes:
            - redisdata:/var/lib/redis/data
        ports:
            - 6379:6379
    api:
        build:
            context: .
            args:
                - DB_HOST=postgresql
                - DB_PORT=5432
                - DB_USER=postgres
                - DB_PASSWORD=password
        ports:
            - 3000:3000
        depends_on:
            - postgresql
            - redis
    nginx:
        restart: unless_stopped
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - nginx:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api

volumes:
    pgdata:
        external: false
    redisdata:
        external: false
