services:
    redis:
        image: redis:7.2-alpine
        restart: always
        volumes:
            - redisdata:/var/lib/redis/data
        ports:
            - 6379:6379
    api:
        build:
            context: .
            args:
                - DB_HOST=bai-db-dev.cl9afysuvjrm.ap-northeast-2.rds.amazonaws.com
                - DB_PORT=5432
                - DB_USER=postgres
                - DB_PASSWORD=
        volumes:
            - $PWD/logs:/app/logs
        ports:
            - 3000:3000
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - $PWD/nginx:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443

volumes:
    pgdata:
        external: false
    redisdata:
        external: false
